#!/bin/bash

if [[ $1 == "page" ]]; then
    if [ -z $2 ] ; then
        echo «Do not set your parameter.»
    else
        mkdir source/app/pages/$2
        cp source/build/page/* source/app/pages/$2
        mv source/app/pages/$2/page.ts source/app/pages/$2/$2.ts
        mv source/app/pages/$2/page.html source/app/pages/$2/$2.html
    fi
elif [[ $1 == "module" ]]; then
    if [ -z $2 ] ; then
        echo «Do not set your parameter.»
    else
        mkdir source/modules/$2
        cp source/build/module/* source/modules/$2
        mv source/modules/$2/default.ts source/modules/$2/$2.ts
        mv source/modules/$2/default.html source/modules/$2/$2.html
        mv source/modules/$2/default.scss source/modules/$2/$2.scss
    fi
else
    echo "Fail $1"
fi