#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'

if [[ $1 == "page" ]]; then
    if [ -z $2 ] ; then
        echo -en "\n${RED}error:"
        tput sgr0
        echo -en " enter the ${YELLOW}name"
        tput sgr0
        echo -en " of page - './add page ${YELLOW}[value]"
        tput sgr0
        echo -en "'\n\n"

    else
        mkdir source/app/pages/$2
        cp source/build/page/* source/app/pages/$2
        mv source/app/pages/$2/page.ts source/app/pages/$2/$2.ts
        mv source/app/pages/$2/page.html source/app/pages/$2/$2.html
        echo -en "\n${GREEN}Page '$2' created...\n"
        echo -en "${GREEN}File '$2/$2.ts' created\n"
        echo -en "${GREEN}File '$2/$2.html' created\n\n"
        tput sgr0
    fi
elif [[ $1 == "module" ]]; then
    if [ -z $2 ] ; then
        echo -en "\n${RED}error:"
                tput sgr0
                echo -en " enter the ${YELLOW}name"
                tput sgr0
                echo -en " of module - './add module ${YELLOW}[value]"
                tput sgr0
                echo -en "'\n\n"
    else
        mkdir source/modules/$2
        cp source/build/module/* source/modules/$2
        mv source/modules/$2/default.ts source/modules/$2/$2.ts
        mv source/modules/$2/default.html source/modules/$2/$2.html
        mv source/modules/$2/default.scss source/modules/$2/$2.scss
        echo -en "\n${GREEN}Module '$2' created...\n"
        echo -en "${GREEN}File '$2/$2.ts' created\n"
        echo -en "${GREEN}File '$2/$2.html' created\n"
        echo -en "${GREEN}File '$2/$2.scss' created\n\n"
        tput sgr0
    fi
else
    if [ -z $1 ] ; then
        echo -en "-------------------------------------------------"
    else
        echo -en "\n${RED}error: "
        tput sgr0
        echo "'$1' is not a add command"
    fi
    echo -en "\nusage: ./add [command] [value]\n\n"
    echo -en "commands:\n"
    echo -en "   page          Create pages in source/app/pages\n"
    echo -en "   module        Create module in source/modules\n\n"
    echo -en "value:           Enter the name of page or module\n\n"
    echo -en "example:         '${YELLOW}./add module search'\n\n"
    echo -en ""
    tput sgr0
fi
